name: Secrets Demo

on:
    push


jobs:
    secrets-check:
        runs-on: ubuntu-latest
        steps:
            - name: check if secret exists
              run: |
               if [ -n "${{ secrets.MY_SECRET_MESSAGE }}" ]; then
                 echo "The secret is set: true"
                 else
                 echo "The secret is NOT set"
                 fi
            - name: try printing secret 
              run: echo "${{ secrets.MY_SECRET_MESSAGE }}"